[package]
name = "http2_client"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-rustls = "0.22"
h2 = "0.3"
hyper = "0.14"
hyper-tls = "0.5"
tracing = "0.1"
tracing-subscriber = "0.2"
structopt = "0.3"
dotenv = "0.15"
serde = { version = "1.0", features = ["derive"] }
