[package]
name = "http2_client"
version = "0.1.0"
edition = "2018"

[dependencies]
hyper = { version = "0.14", features = ["http2", "client"] }
hyper-tls = "0.5"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
structopt = "0.3"
serde = { version = "1", features = ["derive"] }
dotenv = "0.15"
http = "0.2"
rustls = "0.20"
webpki = "0.22"
webpki-roots = "0.22"
tokio-rustls = "0.23"
rustls-native-certs = "0.6"
